var texto = "Blas de Lezo, General de la Armada española, nació en Pasajes, Guipúzcoa, en 1687, y falleció en 1741. Perdió su pierna izquierda por una bala de cañón durante el combate de Vélez Málaga, entre la escuadra francesa del almirante Tolosa, donde él luchaba, y la flota inglesa-holandesa en 1704. A lo largo de su carrera, Blas de Lezo demostró una gran intrepidez en las batallas.\nEn 1713, siendo capitán de navío, Felipe V lo envió a someter la isla de Mallorca. Formó parte de la expedición de la Corona española contra los corsarios en las Antillas y lideró durante 14 años la escuadra y el generalato de los mares del Sur. En reconocimiento a sus servicios, ascendió a jefe de la escuadra.\nEn 1734, fue nombrado teniente general y posteriormente comandante general de los galeones y los navíos Fuerte y Conquistador, enviados a Tierra Firme. El 11 de marzo de 1737, entró con su flota en Cartagena de Indias, tomando posesión del mando de ese apostadero, donde se enteró de la acumulación de fuerzas inglesas en Jamaica.";
draw_set_font(fnt_fuente_museo);
var color = make_color_rgb(196, 163, 56);
draw_set_color(color);
draw_set_valign(fa_top);
draw_set_halign(fa_left);
x = 723;
y = 178;
var ancho = 50;
var alto = 1000;
draw_text_ext(x, y, texto, ancho, alto);
draw_set_valign(fa_top);
draw_set_halign(fa_left);