var bar_x = 487;
var bar_y = 642;
var bar_width = 844;
var bar_height = 145;
var progress_percent = clamp(current_progress / total_progress, 0, 1);
var total_frames = sprite_get_number(spr_barra_de_progreso_sala_15);
var current_frame = round(progress_percent * (total_frames - 1));
var scale_x = bar_width / sprite_get_width(spr_barra_de_progreso_sala_15);
var scale_y = bar_height / sprite_get_height(spr_barra_de_progreso_sala_15);
draw_sprite_ext(spr_barra_de_progreso_sala_15, current_frame, bar_x, bar_y, scale_x, scale_y, 0, c_white, 1);