var texto = "La habilidad de Catalina para comunicarse en ambos idiomas y comprender las costumbres de ambas culturas resultó invaluable. Su papel como intérprete y mediadora contribuyó significativamente a la interacción y negociación entre los conquistadores y los indígenas, facilitando la fundación y consolidación de la ciudad de Cartagena de Indias.\nIndia Catalina dejó un legado duradero en la historia de Cartagena de Indias. Su historia se ha convertido en parte integral del folclore local y en un símbolo de la complejidad del encuentro entre las culturas indígenas y europeas durante el periodo de la conquista. En la actualidad, un monumento en la Plaza de la India Catalina en Cartagena conmemora su contribución única como figura clave en los primeros años de la colonización. La escultura refleja la fusión de elementos indígenas y españoles, simbolizando su papel como un puente entre dos mundos.";
draw_set_font(fnt_fuente_museo);
var color = make_color_rgb(196, 163, 56);
draw_set_color(color);
draw_set_valign(fa_top);
draw_set_halign(fa_left);
x = 723;
y = 178;
var ancho = 50;
var alto = 1000;
draw_text_ext(x, y, texto, ancho, alto);
draw_set_valign(fa_top);
draw_set_halign(fa_left);