var texto = "Las acciones defensivas de Blas de Lezo en Cartagena de Indias fueron cruciales, ya que la ciudad era una presa altamente codiciada por los ingleses. Lezo instaló sus buques en Bocachica para bloquear la entrada al puerto y cerró el acceso con cadenas. Además, desplegó uno de sus cañones más grandes en tierra. Estas medidas mantuvieron a los enemigos alejados durante un tiempo.\nEn 1741, se presentó en Cartagena una escuadra compuesta por 36 buques de guerra y alrededor de 100 transportes, brulotes y bombardas, todos bajo el mando de los almirantes.";
draw_set_font(fnt_fuente_museo);
var color = make_color_rgb(196, 163, 56);
draw_set_color(color);
draw_set_valign(fa_top);
draw_set_halign(fa_left);
x = 723;
y = 178;
var ancho = 50;
var alto = 1000;
draw_text_ext(x, y, texto, ancho, alto);
draw_set_valign(fa_top);
draw_set_halign(fa_left);